# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod properties
mod.name=GlintColorizer
mod.id=glintcolorizer
mod.version=3.0
mod.group=org.polyfrost.glintcolorizer
mod.description=Changes the color of item and block enchantment glints.
mod.source=https://github.com/Polyfrost/GlintColorizer
mod.issues=https://github.com/Polyfrost/GlintColorizer/issues
mod.license=GPL-3.0

# Dependencies
deps.fabric_loader_version=0.17.3
deps.oneconfig_version=1.0.0-alpha.181

# Build Plugins
# in libs.versions.toml

# Minecraft properties
mod.minecraft_version=[VERSIONED]
mod.minecraft_version_range=[VERSIONED]

# Versioned
deps.parchment_version=[VERSIONED]
deps.fabric_api_version=[VERSIONED]