[versions]
kotlin-jvm = "2.2.0"
loom = "1.13-SNAPSHOT"
blossom = "1.3.2"
ksp = "2.2.0-2.0.2"
fletchingtable = "0.1.0-alpha.13"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
loom = { id = "dev.architectury.loom", version.ref = "loom" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
fletchingtable-fabric = { id = "dev.kikugie.fletching-table.fabric", version.ref = "fletchingtable" }